name: Go
on: [push]
jobs:
  review:
    name: Review code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check missing error check
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: make gen && go get -u github.com/kisielk/errcheck; ls -la; errcheck ./...
    - name: Run staticcheck
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: go get honnef.co/go/tools/cmd/staticcheck; staticcheck ./... # https://staticcheck.io/docs/checks
    - name: Run go vet
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: make gen && go vet ./...
  security:
    name: Review security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run gosec
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: go get github.com/securego/gosec/cmd/gosec; make gen && gosec ./... # https://github.com/securego/gosec
  test:
    name: Testable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: make gen && make test
  buildable:
    name: Buildable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: "cedrickring/golang-action@1.3.0"
      env:
        GO111MODULE: "on"
      with:
        args: make gen && make build